### ISSUE TITLE
Are these credentials ok to be here?

### ISSUE THREAD

**Issue by please-wait** [80maker/vuepress-theme-maker#10]
https://github.com/80maker/vuepress-theme-maker/blob/b22b86a8db06754b263420811387b63b9bf64851/blog/.vuepress/config/plugins.js#L85

I am not familiar with this system. From the OAuth-looking interface, these should be changed with an and environmental variable lookup; and if they are in use, the credentials should be rotated.

**Comment by 80maker** [comment]
Oh, you are right. Vssue is a Vue component / plugin, which can enable comments for your static pages. You can refer to it [here](https://vssue.js.org/guide/vuepress.html#vuepress-plugin). Also, you can see [Theme Doc--basic config items](https://80shuo.com/post/2021/01/23/maker-basic.html#blog) for more details.
