### ISSUE TITLE
Adding a `<script>` for client side in a post

### ISSUE THREAD

**Issue by please-wait** [80maker/vuepress-theme-maker#12]
For a particular post, I want to create a `script` tag and run code inside it **on the client side**. So I just put it in the `.md` file and because of it the build process failed. I understand it's because vue is trying to run that script on the server side.

I can't seem to find **a way to make vuepress skip this script and just write it in the built html side the way it is**. I also just need the code for a single post, so I don't want to change anything big.

My question: is there a way to make the theme-maker ignore that script tag? perhaps wrapping it in something? any ideas?

**Comment by 80maker** [comment]
You can try the `custom containers` feature as below.
```
::: demo
<div slot="preview">
  <script>alert(1)</script>
</div>
:::
```

**Comment by please-wait** [comment]
Nice! That actually works pretty nicely. I just have one issue that it escapes the `"` in the code. So instead of `alert("hi")` I get `alert(&quot;hi&quot:)`, which fails. Not a dealbreaker but if you have any suggestions about that I'd appreciate it.
