### ISSUE TITLE
gitee pages 部分资源加载不出来【2】

### ISSUE THREAD

**Issue by 2333Ge** [80maker/vuepress-theme-maker#16]
> 已在1.2.2版本修复;

老板，还是有点问题

首页图片能加载出来，进入文章后头图就加载不出来了
这是我现在部署的地址：

https://i2333g3.gitee.io/personal-learning-blog/post/2022/04/21/shell.html

左侧头像加载不出
从首页进文章页后，刷新地址变成了：https://i2333g3.gitee.io/personal-learning-blog/post/2022/04/21/logo.jpg 了

应该是 https://i2333g3.gitee.io/personal-learning-blog/logo.jpg

_Originally posted by @2333Ge in https://github.com/80maker/vuepress-theme-maker/issues/15#issuecomment-1180124542_

**Comment by 80maker** [comment]
1.左侧头像加载不出应该是配置没对，不能用相对路径;
2.已在1.2.3修复;

**Comment by 2333Ge** [comment]
> 1.左侧头像加载不出应该是配置没对，不能用相对路径; 2.已在1.2.3修复;

配置和demo中一样，写得`./logo.jpg`,图片在public下

这是项目的配置：[config.js](https://gitee.com/i2333g3/personal-learning/blob/master/blog/.vuepress/config.js)

**Comment by 80maker** [comment]
你可以用/logo.jpg解决，一定要追究的话就是demo没有用基础路径这种场景，vuepress是没有为相对路径自动转换添加基础路径的能力的，这个也并不合理。
