### ISSUE TITLE
Build fails because `$Pagination` in `Home.vue` gives `null`

### ISSUE THREAD

**Issue by please-wait** [80maker/vuepress-theme-maker#9]
This is [pointed out in the Vuepress documentation](https://vuepress-plugin-blog.ulivz.com/client-api/#pagination):

> WARN
>
> Note that if you're accessing $pagination at a route which doesn't match any classification, the value of $pagination will be null.
>
> So when you develop layout components, you need to verify that $pagination exists.

Build fails because it can't find `items in $pagination.pages`. Looks like a problem with the config file?

**Comment by please-wait** [comment]
Looks like #8 fixes it.

**Comment by 80maker** [comment]
Thanks for fixing this! The `blog`  directory was originally used as a test demo, and some configuration items are out of date.

**Comment by please-wait** [comment]
My pleasure. Closing this for now.
